# Generated by Django 5.1.7 on 2025-03-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=7777777, max_length=500),
            preserve_default=False,
        ),
    ]
