# Generated by Django 5.1.7 on 2025-03-26 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
