# Generated by Django 5.2.6 on 2025-09-30 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_cartorder_buyer_alter_cartorder_vendor_and_more'),
        ('userauth', '0002_remove_customerprofile_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerProfile',
        ),
        migrations.DeleteModel(
            name='VendorProfile',
        ),
    ]
