# Generated by Django 5.2.6 on 2025-10-26 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor')], default='customer', max_length=10),
        ),
    ]
