# Generated by Django 5.1.7 on 2025-03-28 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_category', to='store.subcategory'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='title',
            field=models.CharField(choices=[('SHIRTS', 'Shirts'), ('T_SHIRTS', 'T-Shirts'), ('JEANS', 'Jeans'), ('TROUSERS', 'Trousers'), ('SUITS', 'Suits'), ('TOPS', 'Tops'), ('JEANS', 'Jeans'), ('SKIRTS', 'Skirts'), ('LEGGINGS', 'Leggings'), ('JACKETS', 'Jackets'), ('HOODIES', 'Hoodies'), ('SHORTS', 'Shorts'), ('JOGGERS', 'Joggers')], default='T-shirt', max_length=100),
        ),
    ]
