# Generated by Django 5.1.7 on 2025-03-31 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_tax_options_alter_cart_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='title',
            field=models.CharField(choices=[('SHIRTS', 'Shirts'), ('T_SHIRTS', 'T-Shirts'), ('JEANS', 'Jeans'), ('TROUSERS', 'Trousers'), ('SUITS', 'Suits'), ('TOPS', 'Tops'), ('JEANS', 'Jeans'), ('SKIRTS', 'Skirts'), ('LEGGINGS', 'Leggings'), ('JACKETS', 'Jackets'), ('HOODIES', 'Hoodies'), ('SHORTS', 'Shorts'), ('JOGGERS', 'Joggers'), ('DRESS', 'Dress')], default='T-shirt', max_length=100),
        ),
    ]
