# Generated by Django 5.2.6 on 2025-10-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_cartorder_buyer_alter_cartorderitem_vendor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='title',
            field=models.CharField(choices=[('SHIRTS', 'Shirts'), ('T-SHIRTS', 'T-Shirts'), ('JEANS', 'Jeans'), ('TROUSERS', 'Trousers'), ('SUITS', 'Suits'), ('TOPS', 'Tops'), ('SKIRTS', 'Skirts'), ('LEGGINGS', 'Leggings'), ('JACKETS', 'Jackets'), ('HOODIES', 'Hoodies'), ('SHORTS', 'Shorts'), ('JOGGERS', 'Joggers'), ('DRESS', 'Dress'), ('SWEATSHIRTS', 'Sweatshirts'), ('COATS', 'Coats')], default='T-shirt', max_length=100),
        ),
    ]
