# Generated by Django 5.2.6 on 2025-10-02 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_subcategory_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='color',
            name='color_code',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='title',
            field=models.CharField(choices=[('SHIRTS', 'Shirts'), ('T-SHIRTS', 'T-Shirts'), ('JEANS', 'Jeans'), ('TROUSERS', 'Trousers'), ('SUITS', 'Suits'), ('TOPS', 'Tops'), ('SKIRTS', 'Skirts'), ('LEGGINGS', 'Leggings'), ('JACKETS', 'Jackets'), ('HOODIES', 'Hoodies'), ('SHORTS', 'Shorts'), ('JOGGERS', 'Joggers'), ('DRESS', 'Dress'), ('SWEATSHIRTS', 'Sweatshirts')], default='T-shirt', max_length=100),
        ),
    ]
