# Generated by Django 5.2.6 on 2025-10-05 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_cartorder_buyer_alter_color_color_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='Pending', max_length=100),
        ),
    ]
